### ISSUE TITLE
very high data volume request link (subhr, native grid, hundred of years) (DR 01.00.13)

### ISSUE THREAD

**Issue by senesis** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#206]
That request link (at http://clipc-services.ceda.ac.uk/dreq/u/33b0f666-a27a-11e6-bfbb-ac72891c3257__00.html) includes 79 variables , among which some are 3D; this for 8 experiments, among which piControl for 165 years
The grid is mentionned there as 'native', which would lead to very large data volumes.
Can we safely assume that grid actually should reaf 'cfsites' ?

**Comment by martinjuckes** [comment]
Yes .. the "grid" value is irrelevant here .. I'll remove it to avoid confusion.

**Comment by senesis** [comment]
As far as I understand, it IS relevant when the spatial structure of the CMOR variables indicates a global field. Isnt' it ?

**Comment by martinjuckes** [comment]
That is correct, it is the dimensions specified which you need to worry about. I see there is one variable with the wrong dimensions specified (rsucs)

**Comment by martinjuckes** [comment]
This is fixed for release 01.00.15

**Comment by senesis** [comment]
Actually, in DR 01.00.15, 'rsucs' in table CFSubhr still shows shape "S-na" , while it should be "S-AH", like for 'rsu' (see http://clipc-services.ceda.ac.uk/dreq/u/a955260e-817c-11e6-a4e2-5404a60d96b5.html)
