### ISSUE TITLE
fbddtalk (and others) Emon - vertical integral, on model levels?

### ISSUE THREAD

**Issue by jkettleb** [cmip6dr/CMIP6_DataRequest_VariableDefinitions#295]
fbddtalk Emon has the descirption:

'vertical integral of net biological terms in time rate of change of alkalinity'

standard_name:
`integral_wrt_depth_of_tendency_of_sea_water_alkalinity_expressed_as_mole_equivalent_due_to_biological_processes`

yet is dimensioned:

`dimids[i]: [grids] longitude [dim:longitude]; latitude [dim:latitude]; olevel [dim:olevel]`

should the olevel be present?

I think this applies to other diagnostics such as fddtdife too

**Comment by martinjuckes** [comment]
The variables in question are: fddtalk, fddtdife,fddtdisi, fddtdic, fddtdin, fddtdip, fbddtalk, fbddtdife,fbddtdisi, fbddtdic, fbddtdin, fbddtdip. I'll check with Chris Jones to see if they are needed on all levels.

**Comment by martinjuckes** [comment]
Fixed in 01.00.24  .. these variables should be the same for C4MIP and OMIP.

**Comment by klindsay28** [comment]
As of 01.00.27, fddtalk in Emon appears to still have a dimension discrepancy.
fddtalk in Omon appears to be fine.

**Comment by klindsay28** [comment]
@martinjuckes, is it feasible to get the lingering discrepancy for `fddtalk` in Emon corrected in 01.00.28, perhaps by removing it from Emon (`fddtalk` is in Omon)?

**Comment by martinjuckes** [comment]
OK, this is fixed now.
